#! /bin/bash

FwDir=/opt/fw-tools

CfDirs="/etc/auth-monitor $FwDir/etc"
for dir in $CfDirs
do
  if [ -f "$dir/auth-monitor.conf" ]
  then
    ConfDir=$dir
    break
  fi
done

if [ -z "$ConfDir" ]
then
  echo "* fw-tools configuration file not found"
  exit 1
fi

DataDir=$FwDir/var

Echo=echo
[ "$USER" == "root" ] && Echo=

FName=friends.txt
FileIn="$DataDir/$FName"
FileCf="$ConfDir/auth-monitor.conf"

awk '
  BEGIN { fTag = 0 }
  /<\/network>/ { fTag = 0 }
  fTag == 1 { print $0 }
  /<network friends>/ { fTag = 1 }
' $FileCf > $FileIn
[ -f $FileIn ] || exit 1

Chain=Friends

Friends=$(grep -v '#' $FileIn)

declare -i nAddr
$Echo iptables -F $Chain
for ip in $Friends
do
  $Echo iptables -A $Chain -p tcp -s $ip -j ACCEPT
  nAddr=$nAddr+1
done

printf "Number of Friends... %d\n" $nAddr

